
.build: &build_core
  stage: build
  image: maven:3.3.3-jdk-8
  script: 
  - mvn package
  - cp lutra-cli/target/lutra.jar lutra.jar
  artifacts:
    paths:
    - lutra.jar

build_develop:
  <<: *build_core
  only: 
    - develop
  artifacts:
    expire_in: 3 mos 1day

build_tags:
  <<: *build_core
  only: 
    - tags
