
variables:
  GIT_SUBMODULE_STRATEGY: normal

.build: &build_core
  stage: build
  image: maven:3.3.3-jdk-8
  script:
  - cd gaupa; mvn install; cd ..
  - mvn install package
  - cp lutra-cli/target/lutra.jar lutra.jar

snapshot:
  <<: *build_core
  only:
    - develop
    - master
  artifacts:
    expire_in: 6 mos 1day
    paths:
    - lutra.jar

release:
  <<: *build_core
  only: 
    - tags
  artifacts:
    paths:
    - lutra.jar

codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]
