
image: maven:3.3.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

snapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests -Dcheckstyle.skip=true -Dpmd.skip=true
    - cp lutra-cli/target/lutra.jar lutra.jar
  only:
    - develop
    - master
  artifacts:
    expire_in: 6 mos 1day
    paths:
      - lutra.jar

release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests -Dcheckstyle.skip=true -Dpmd.skip=true
    - cp lutra-cli/target/lutra.jar lutra.jar
  only: 
    - tags
  artifacts:
    paths:
    - lutra.jar

codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]
